// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dpthlcrumrowdaocifxy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwdGhsY3J1bXJvd2Rhb2NpZnh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MjgwNDEsImV4cCI6MjA2MDEwNDA0MX0.1A-QwFRoxLUSHo3QKjNa3JS77Au-3XvwSnskyspWy9Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);